name: Gerar Versão Automática

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Gerar versão semântica
        id: version
        uses: paulhatch/semantic-version@v5
        with:
          branch: main
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          patch_pattern: "fix:"
          version_format: "${major}.${minor}"

      - name: Criar variável de versão
        run: echo "VERSION=${{ steps.version.outputs.version }}" >> $GITHUB_ENV

      - name: Exibir versão no rodapé do blog
        run: echo "Versão: $VERSION"
